import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
export default function Home() {
  return (
    <div className="">
      <Head>
        <title>AirBnB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>

      <Header/>
      {/* Banner */}
      
    </div>
  )
}
